### ISSUE TITLE
after a while metrics stop refreshing

### ISSUE THREAD

**Issue by thibaut-fagart** [thibaut-fagart/screeps-grafana#1]
running docker logs shows the following errror

```
{ request:
   { debugId: 8615,
     uri: 'https://screeps.com/api/auth/signin',
     method: 'POST',
     headers:
      { host: 'screeps.com',
        accept: 'application/json',
        'content-type': 'application/json',
        'content-length': 70 },
     body: '{...... } }
Unhandled rejection RequestError: Error: getaddrinfo EMFILE screeps.com:443
  at new RequestError (/usr/src/app/node_modules/request-promise/lib/errors.js:11:15)
  at Request.RP$callback [as _callback] (/usr/src/app/node_modules/request-promise/lib/rp.js:60:32)
  at self.callback (/usr/src/app/node_modules/request-promise/node_modules/request/request.js:199:22)
  at emitOne (events.js:77:13)
  at Request.emit (events.js:169:7)
  at Request.onRequestError (/usr/src/app/node_modules/request-promise/node_modules/request/request.js:821:8)
  at emitOne (events.js:77:13)
  at ClientRequest.emit (events.js:169:7)
  at TLSSocket.socketErrorListener (_http_client.js:258:9)
  at emitOne (events.js:77:13)
  at TLSSocket.emit (events.js:169:7)
  at connectErrorNT (net.js:998:8)
  at nextTickCallbackWith2Args (node.js:441:9)
  at process._tickCallback (node.js:355:17)
```

**Comment by thibaut-fagart** [comment]
fixed with updated version from screepers
